objc: true
clean: true
sdk: iphonesimulator

theme: ../../Themes/apple

module: AppCenterIdentity
module_version: 1.13.0
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Identity.md
documentation: ../../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../../AppCenter-SDK-Apple/iOS/AppCenterIdentity.framework/Headers/AppCenterIdentity.h
framework_root: ../../../AppCenter-SDK-Apple/iOS/
exclude: [../../../AppCenter-SDK-Apple/iOS/AppCenterIdentity.framework/Headers/MSService.h, ../../../AppCenter-SDK-Apple/iOS/AppCenterIdentity.framework/Headers/MSServiceAbstract.h]

root_url: https://docs.microsoft.com/appcenter/sdk/ios
github_url: https://github.com/Microsoft/AppCenter-SDK-Apple
github_file_prefix: "https://github.com/Microsoft/AppCenter-SDK-Apple"

skip_undocumented: true

output: Generated/
