objc: true
clean: true
sdk: appletvsimulator

theme: ../../Themes/apple

module: AppCenterCrashes
module_version: 0.14.1
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/Crashes.md
documentation: ../../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../../AppCenter-SDK-Apple/tvOS/AppCenterCrashes.framework/Headers/AppCenterCrashes.h
framework_root: ../../../AppCenter-SDK-Apple/tvOS/
exclude: [../../../AppCenter-SDK-Apple/tvOS/AppCenterCrashes.framework/Headers/MSService.h, ../../../AppCenter-SDK-Apple/tvOS/AppCenterCrashes.framework/Headers/MSServiceAbstract.h]

root_url: http://docs.mobile.azure.com/sdk/ios
github_url: https://github.com/Microsoft/mobile-center-sdk-ios
github_file_prefix: "https://github.com/Microsoft/mobile-center-sdk-ios"

skip_undocumented: true

output: Generated/
