codecov:
  bot: xabldint
ignore:
  - "Vendor/**/*"
  - "MobileCenter/MobileCenterTests/**/*"
  - "MobileCenterAnalytics/MobileCenterAnalyticsTests/**/*"
  - "MobileCenterCrashes/MobileCenterCrashesTests/**/*"
  - "MobileCenterDistribute/MobileCenterDistributeTests/**/*"
  - "MobileCenterPush/MobileCenterPushTests/**/*"
