objc: true
clean: true
sdk: macosx

theme: ../../Themes/apple

module: AppCenter
module_version: 0.14.1
author: Microsoft Corp
author_url: http://www.microsoft.com

readme: Guides/AppCenter.md
documentation: ../../Guides/[^index]*.md
custom_categories:
  - name: Guides
    children:
    - Installation

umbrella_header: ../../../MobileCenter-SDK-Apple/macOS/AppCenter.framework/Headers/MobileCenter.h
framework_root: ../../../MobileCenter-SDK-Apple/macOS/

root_url: http://docs.mobile.azure.com/sdk/ios
github_url: https://github.com/Microsoft/mobile-center-sdk-ios
github_file_prefix: "https://github.com/Microsoft/mobile-center-sdk-ios"

skip_undocumented: true

output: Generated/
